footer:
  rails_href: "https://www.railstutorial.org/"
  michael_hartl: "https://www.michaelhartl.com/"
  new: "https://news.railstutorial.org/"
about:
  rails_href: "https://www.railstutorial.org/"
  learn_enough: "https://www.learnenough.com/"
  book: "https://www.learnenough.com/"
  creencast_series: "https://screencasts.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
contact:
  contact_page: "https://www.railstutorial.org/contact"
help:
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
home:
  rails_help: "https://www.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
edit:
  edit_user: "https://gravatar.com/emails"
user:
  email_length: !ruby/range 6..255
  name_max: 50
  pass_min: 6
  valid_email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  page_item: 50
  pagy_page: 20
helpers:
  users_size: 80
password_reset:
  expired: 2
micropost:
  content_max: 140
  accept_path: "image/jpeg,image/gif,image/png"
  size: 50
  image_path: ["image/jpeg", "image/gif", "image/png"]
  resize_to_limit: [500, 500]
  image_size: 5
user_info:
  size: 50
show_follow:
  user.size: 30
